version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SHA256_PASS=${SHA256_PASS}
      - HASH_SALT=${HASH_SALT}
      - TRUSTED_ORIGINS=${TRUSTED_ORIGINS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

  db: 
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

# volumes:
#   mediafiles:
#     driver_opts:
#       type: cifs
#       o: username=${SMB_USER},password=${SMB_PASS},uid=${GUID},gid=${GUID},vers=3.0
#       device: ${MEDIAFILES_PATH}

#   staticfiles:
#     driver_opts:
#       type: cifs
#       o: username=${SMB_USER},password=${SMB_PASS},uid=${GUID},gid=${GUID},vers=3.0
#       device: ${STATICFILES_PATH}