# Generated by Django 4.0.3 on 2022-03-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('epoch', models.FloatField()),
                ('file', models.FileField(upload_to='')),
                ('filename', models.CharField(max_length=200)),
                ('uploader', models.CharField(default='ADMIN', max_length=50)),
            ],
        ),
    ]
