# Generated by Django 4.0.5 on 2022-07-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewclips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='feed',
            field=models.BooleanField(default=True),
        ),
    ]
